language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - cd MS2/DB/portalocker/ && python setup.py install && cd -
script:
    - py.test
after_success:
    - coveralls
